run_config:
  name: random-forest-featset-1
  author: Sharika Mahadevan
  version: default
  description: Classifies clouds into one of two types.
  dependencies: requirements.txt
  data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
  output: runs
create_dataset: ['visible_mean', 'visible_max', 'visible_min', 
        'visible_mean_distribution', 'visible_contrast', 
        'visible_entropy', 'visible_second_angular_momentum', 
        'IR_mean', 'IR_max', 'IR_min']
generate_features:
  calculate_norm_range:
    IR_norm_range:
      min_col: IR_min
      max_col: IR_max
      mean_col: IR_mean
  calculate_range:
    IR_range:
      min_col: IR_min
      max_col: IR_max
  calculate_log_transform:
    log_transform:
      log_entropy: visible_entropy
  calculate_entropy:
    entropy_x_contrast:
      col_a: visible_contrast
      col_b: visible_entropy
train_model:
  split_data:
    test_size: 0.3
    random_state: 250
  choose_features:
    features_to_use: ['log_entropy', 'IR_norm_range', 'entropy_x_contrast']
  get_target:
    target_feature: class
  model_training:
    n_estimators: 10
    max_depth: 10
score_model:
  choose_features:
    features_to_use: ['log_entropy', 'IR_norm_range', 'entropy_x_contrast']
  get_target:
    target_feature: class
  score_type: 
    probability: pred_probability
    label: pred_label
    truth: true_label
evaluate_performance:
  score_type: 
    probability: pred_probability
    label: pred_label
    truth: true_label
  metric_type:
    auc: auc
    confusion: confusion_matrix
    accuracy: accuracy
    classification_report: classification_report
aws:
  upload: True
  bucket_name: smv7369-clouds-hw2
  region_name: us-east-2