aws:
  bucket_name: smv7369-clouds-hw2
  region_name: us-east-2
  upload: true
create_dataset:
- visible_mean
- visible_max
- visible_min
- visible_mean_distribution
- visible_contrast
- visible_entropy
- visible_second_angular_momentum
- IR_mean
- IR_max
- IR_min
evaluate_performance:
  metric_type:
    accuracy: accuracy
    auc: auc
    classification_report: classification_report
    confusion: confusion_matrix
  score_type:
    label: pred_label
    probability: pred_probability
    truth: true_label
generate_features:
  calculate_entropy:
    entropy_x_contrast:
      col_a: visible_contrast
      col_b: visible_entropy
  calculate_log_transform:
    log_transform:
      log_entropy: visible_entropy
  calculate_norm_range:
    IR_norm_range:
      max_col: IR_max
      mean_col: IR_mean
      min_col: IR_min
  calculate_range:
    IR_range:
      max_col: IR_max
      min_col: IR_min
run_config:
  author: Sharika Mahadevan
  data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
  dependencies: requirements.txt
  description: Classifies clouds into one of two types.
  name: random-forest-featset-1
  output: runs
  version: default
score_model:
  choose_features:
    features_to_use:
    - log_entropy
    - IR_norm_range
    - entropy_x_contrast
  get_target:
    target_feature: class
  score_type:
    label: pred_label
    probability: pred_probability
    truth: true_label
train_model:
  choose_features:
    features_to_use:
    - log_entropy
    - IR_norm_range
    - entropy_x_contrast
  get_target:
    target_feature: class
  model_training:
    max_depth: 10
    n_estimators: 10
  split_data:
    random_state: 250
    test_size: 0.3
